const fs = require('fs').promises;
const { infos } = require('./database.js')

//Epic
const epic = async (req, res) => {
  let epic = await infos.findOne({ "_id": "epic" })
  let json = JSON.parse(epic.json);

  let meme = json.map(a => {
    return `<item>
      <title>${a.name}</title>
      <link>${a.link}</link>
      <guid>${a.id}</guid>
      <enclosure url="${a.img}"/>
    </item>`
  })

  const content = `<?xml version="1.0" encoding="UTF-8"?>
    <rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
    <channel>
    <title>RSS</title>
    <description>RSS Feed - Generated by: Asana#0001 (Discord)</description>
    <language>br</language>
    ${meme.join('')}
    </channel>
    </rss>`

  res.type('application/xml').send(content)
}

//BetterAnime
const betteranime = async (req, res) => {
  let better = await infos.findOne({ "_id": "better" })
  let json = JSON.parse(better.json);

  let meme = json.map(a => {
    return `<item>
      <title>${a.name}</title>
      <link>${a.link}</link>
      <guid>${a.link}</guid>
      <pubDate>${a.date}</pubDate>
      <enclosure url="${a.img}"/>
    </item>`
  })

  const content = `<?xml version="1.0" encoding="UTF-8"?>
    <rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
    <channel>
    <title>RSS</title>
    <description>RSS Feed - Generated by: Asana#0001 (Discord)</description>
    <language>br</language>
    ${meme.join('')}
    </channel>
    </rss>`

  res.type('application/xml').send(content)
}

//9anime
const animeto = async (req, res) => {
  let animeto = await infos.findOne({ "_id": "9anime" })
  let json = JSON.parse(animeto.json);

  let meme = json.map(a => {
    return `<item>
      <title>${a.name}</title>
      <link>${a.link}</link>
      <guid>${a.guid}</guid>
      <pubDate>${a.date}</pubDate>
      <enclosure url="${a.img.replace('-w100', '')}"/>
    </item>`
  })

  const content = `<?xml version="1.0" encoding="UTF-8"?>
    <rss xmlns:atom="http://www.w3.org/2005/Atom" xmlns:content="http://purl.org/rss/1.0/modules/content/" version="2.0">
    <channel>
    <title>RSS</title>
    <description>RSS Feed - Generated by: Asana#0001 (Discord)</description>
    <language>br</language>
    ${meme.join('')}
    </channel>
    </rss>`

  res.type('application/xml').send(content)
}

module.exports = { betteranime, epic, animeto }
